version: "3.9"

services:
  gateway:
    image: docker/mcp-gateway:latest
    command:
      - --servers=duckduckgo
      - --servers=github-official
      - --transport=streamable        # or: --transport=sse
      - --port=8811
      - --catalog=/mcp/catalogs/custom.yaml
      - --config=/mcp/config.yml   
      - --registry=/mcp/registry.yml  
      - --tools-config=/mcp/tools.yml
      - --secrets=mcp:/run/secrets/mcp_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mcp:/mcp
    ports:
      - "8811:8811"
    secrets:
      - mcp_secret
    restart: unless-stopped

secrets:
  mcp_secret:
    file: .env   # this file's CONTENT becomes the secret
