version: "3.9"

services:
  gateway:
    image: docker/mcp-gateway:latest
    command:
      - --servers=duckduckgo,dice
      - --catalog=/mcp/catalogs/official-catalog.yml
      - --catalog=/mcp/catalogs/custom.yml
      - --transport=streamable        # or: --transport=sse
      - --port=8811
      - --secrets=mcp:/run/secrets/mcp_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mcp:/mcp
    ports:
      - "8811:8811"
    secrets:
      - mcp_secret
    restart: unless-stopped

secrets:
  mcp_secret:
    file: .env   # this file's CONTENT becomes the secret
